### ISSUE TITLE
Review Ticket Week 1

### ISSUE THREAD

**Issue by Navodit1603** [ChristopherDuroiu/usb-c#15]
* [x] Design - Wiki Theme, Brain Write & Wire Frame
* [x] Technicals - 10  to 12 key ideas 
* [x] Github - On Wiki containing Management Plan, forking, branching, pull request, etc
* [x] Deployment - On Wiki containing Hardware, frequency, etc
* [x] Scrum Board - Assignments and Backlog

**Comment by rpeddakama** [comment]
Design - wireframe is well made and shows the design for multiple pages on the website. Ideation is clear. Everything is easily found in the README
Technicals - Unique features shown in the README (11)
Github - Well explained and organized.
Deployment - The deployment plan is good but I see no mention of frequency: -0.05
Scrum Board -  Well organized - each task is specifically assigned and has subtasks to avoid confusion.

Overall: 4.95/5

**Comment by jm1021** [comment]
USBC - Navodit. 5/5
* Nice wires added into Wiki 1/1
* Nice capture of Ideas in README 1/1
* Plan looks good 1/1
* Deployment plan looks good.  Action so somebody else can do update 1/1
* Scrum Board Active 1/1

Frequency and release day criteria could be handled better.
