### ISSUE TITLE
Week 2 Review

### ISSUE THREAD

**Issue by Navodit1603** [ChristopherDuroiu/usb-c#21]
Total Scores:

- Navodit: 8.25/9
- Grace: 8.25/9
- Caleb: 8.25/9
- Chris: 8.25/9

**Comment by calebkimsd** [comment]
Individual - CALEB KIM
About Pages on deployed on Site

- [x] 1.0
- [ ] .75
- [ ] .5
- [ ] 0
Justification:  The about page is present right on the website.
<img width="713" alt="image" src="https://user-images.githubusercontent.com/89210382/145623546-34e9e609-7272-4fa4-ace8-89e43ccc97fd.png">

Page must use a Layout and have special customization (color pallet, background, etc)

- [x] 1.0
- [ ] .75
- [ ] .5
- [ ] 0
Justification: More facts about me at the bottom.
<img width="664" alt="image" src="https://user-images.githubusercontent.com/89210382/145619444-71465972-289e-4d29-b9b2-3af3d76e4c73.png">

A picture with a Mask that toggles to Picture of Choice (ie pic without mask). Perhaps ASCII art.

- [x] 1.0
- [ ] .75
- [ ] .5
- [ ] 0
Justification: Click on image to toggle between mask/no mask.
<img width="212" alt="image" src="https://user-images.githubusercontent.com/89210382/145619170-63b83d6a-76f0-4987-bc60-1f38cb570b23.png">

Pull or show data (Web API) with information of interest

- [x] 1.0
- [ ] .75
- [ ] .5
- [ ] 0
Justification: API from RapidAPIs that pulls data in a question/answer format.
<img width="728" alt="image" src="https://user-images.githubusercontent.com/89210382/145619128-3df81734-2658-4d8c-8357-2e2f0a8dfa9f.png">

Establish link(s) to journal and other key indicators of your work and progress on your home page (remember Tri 1 pop quiz)

- [x] 1.0
- [ ] .75
- [ ] .5
- [ ] 0
Justification: 
<img width="97" alt="image" src="https://user-images.githubusercontent.com/89210382/145621198-40565f73-68f1-4201-b4f8-2f413ef914d7.png">

Store and Retrieve Data

- [ ] 1.0
 - [x] .75
 - [ ] .5
- [ ] 0
Justification: A database skeleton is present that works and stores data that is being used.
<img width="260" alt="image" src="https://user-images.githubusercontent.com/89210382/145618984-f7b10c3a-c04c-46bd-a968-24dc952c4276.png">

Unit 2 FRQ deployed

- [ ] 1.0
- [x] .75
- [ ] .5
- [ ] 0
Justification: Trouble implementing the FRQ with greet/fibonacci so I ended up just embedding the code onto my about me page. 
<img width="218" alt="image" src="https://user-images.githubusercontent.com/89210382/145619030-e82c875e-b707-4243-90ef-ebfbc32b1e8a.png">

**Comment by ChristopherDuroiu** [comment]
Individual
About Pages on deployed on Site

- [x] 1.0
- [ ] .75
- [ ] .5
- [ ] 0
Justification: My about page is up and running, but it does not look very professional and some style changes are still necessary.
![image](https://user-images.githubusercontent.com/89252299/145622342-f0119c7e-f023-43a2-9c5c-452912e2aa96.png)

Page must use a Layout and have special customization (color pallet, background, etc)

- [x] 1.0
- [ ] .75
- [ ] .5
- [ ] 0
Justification: 
![image](https://user-images.githubusercontent.com/89252299/145622245-12eb6424-0f14-41ca-a064-6b178f4aa4b6.png)

Picture with Mask that toggles to Picture of Choice (ie pic without mask). Perhaps ASCII art.

- [x] 1.0
- [ ] .75
- [ ] .5
- [ ] 0
Justification: Picture of choice works flawlessly.
![image](https://user-images.githubusercontent.com/89252299/145622165-5a0704e6-844b-41ce-b1db-efd10bd8e142.png)


Pull or show data (Web API) with information of interest

- [x] 1.0
- [ ] .75
- [ ] .5
- [ ] 0
Justification: All trivia links up and running
![image](https://user-images.githubusercontent.com/89252299/145622373-d531acfc-d965-4862-8cba-11a269fae399.png)

Establish link(s) to journal and other key indicators of your work and progress on your home page (remember Tri 1 pop quiz)

- [x] 1.0
- [ ] .75
- [ ] .5
- [ ] 0
Justification: Box of contributions on readme like the tri one pop quiz
Store and Retrieve Data

- [ ] 1.0
 - [x] .75
 - [ ] .5
- [ ] 0
Justification: Our API and trivia forms are up and running but mine still needs to be cleaned up and look better on the frontend. Also I have yet to make a JSON file to store data on comments but actually comment code is finished.
![image](https://user-images.githubusercontent.com/89252299/145622455-eb5cda4c-d4ea-4168-8092-eb85c288ff97.png)

Unit #2 FRQ deployed

- [ ] 1.0
- [x] .75
- [ ] .5
- [ ] 0
Justification: FRQ implementation is done as seen above with time [] manipulation but we do not have a deployed site yet.

TOTAL: 7.5/8

**Comment by gracele246** [comment]
Individual
About Pages on deployed on Site
- [x] 1.0
- [ ] .75
- [ ] .5
- [ ] 0
Justification:
![image](https://user-images.githubusercontent.com/73254122/145622682-ed0147d1-0119-402c-b07d-815d6a2f8987.png)


Page must use a Layout and have special customization (color pallet, background, etc)
- [x] 1.0
- [ ] .75
- [ ] .5
- [ ] 0
Justification:
![image](https://user-images.githubusercontent.com/73254122/145622573-494dad76-30d5-477a-9f53-02d93ec7db2d.png)

Picture with Mask that toggles to Picture of Choice (ie pic without mask). Perhaps ASCII art.
- [x] 1.0
- [ ] .75
- [ ] .5
- [ ] 0
Justification:
![image](https://user-images.githubusercontent.com/73254122/145621500-3daaa80d-e69d-4f16-8126-77cd5017576e.png)

Pull or show data (Web API) with information of interest
- [x] 1.0
- [ ] .75
- [ ] .5
- [ ] 0
Justification:
[API Code](https://github.com/ChristopherDuroiu/usb-c/blob/6d5e3dbf64dbeed3b633f6f7f150634af7b5c102/src/main/java/com/example/sping_portfolio/controllers/grace/Grace.java#L19-L39)
![image](https://user-images.githubusercontent.com/73254122/145622846-531397c2-f526-4b99-992e-45665dc5a6c2.png)


Establish link(s) to journal and other key indicators of your work and progress on your home page (remember Tri 1 pop quiz)

- [x] 1.0
- [ ] .75
- [ ] .5
- [ ] 0
Justification:
![image](https://user-images.githubusercontent.com/73254122/145622312-90ba68e3-0d9a-4929-a8de-f7cfabfb72f6.png)

Store and Retrieve Data
- [ ] 1.0
- [x] .75
- [ ]  - [ ] .5
- [ ] 0
Justification:
![image](https://user-images.githubusercontent.com/73254122/145621887-cca17903-bd81-44be-a11d-9016961e6514.png)

- [ ] 1.0
- [x] .75
- [ ] .5
- [ ] 0
Justification:
[Unit #2 ](https://github.com/ChristopherDuroiu/usb-c/issues/7#issue-1056411483)

**Comment by gracele246** [comment]
[Unit 2 Plan](https://github.com/ChristopherDuroiu/usb-c/issues/7#issue-1056411483)

**Comment by Navodit1603** [comment]
Individual

About Pages on deployed on Site

- [x] 1.0
- [ ] .75
- [ ] .5
- [ ] 0
Justification:
- [Navodit's About me page](https://github.com/ChristopherDuroiu/usb-c/blob/main/src/main/java/com/example/sping_portfolio/controllers/navodit/Navodit.java)
- [Navodit About Me HTML](https://github.com/ChristopherDuroiu/usb-c/blob/main/src/main/resources/templates/navodit.html) 


Page must use a Layout and have special customization (color pallet, background, etc)

- [x] 1.0
- [ ] .75
- [ ] .5
- [ ] 0
Justification: 

<img width="1439" alt="Screen Shot 2021-12-10 at 9 51 20 AM" src="https://user-images.githubusercontent.com/54903217/145619090-c799792d-a38a-442c-8f4f-554945184fc2.png">

Picture with Mask that toggles to Picture of Choice (ie pic without mask). Perhaps ASCII art.

- [x] 1.0
- [ ] .75
- [ ] .5
- [ ] 0
Justification: 
<img width="1439" alt="Screen Shot 2021-12-10 at 9 51 20 AM" src="https://user-images.githubusercontent.com/54903217/145619090-c799792d-a38a-442c-8f4f-554945184fc2.png">

<img width="1433" alt="Screen Shot 2021-12-10 at 9 52 58 AM" src="https://user-images.githubusercontent.com/54903217/145619319-d9e63a96-4b36-4ad0-b7df-08982ad51f17.png">

Pull or show data (Web API) with information of interest

- [x] 1.0
- [ ] .75
- [ ] .5
- [ ] 0
Justification: 
- [Navodit's About me page](https://github.com/ChristopherDuroiu/usb-c/blob/main/src/main/java/com/example/sping_portfolio/controllers/navodit/Navodit.java)
- <img width="1439" alt="Screen Shot 2021-12-10 at 9 54 37 AM" src="https://user-images.githubusercontent.com/54903217/145619558-cca63ea9-9742-4be2-89bb-9c5d954a058f.png">

Establish link(s) to journal and other key indicators of your work and progress on your home page (remember Tri 1 pop quiz)

- [x] 1.0
- [ ] .75
- [ ] .5
- [ ] 0
Justification:

<img width="1438" alt="Screen Shot 2021-12-10 at 10 12 10 AM" src="https://user-images.githubusercontent.com/54903217/145621734-e3e035c3-9372-4b04-8d85-20b741328d3e.png">

Store and Retrieve Data

- [ ] 1.0
- [x] .75
- [ ] .5
- [ ] 0
Justification: 
- DB is implemented on the site. However, we do not have a JSON file.
- [UserComments](https://github.com/ChristopherDuroiu/usb-c/blob/main/src/main/java/com/example/sping_portfolio/controllers/chris/UserComment.java)
- [Comments](https://github.com/ChristopherDuroiu/usb-c/blob/main/src/main/java/com/example/sping_portfolio/controllers/chris/Comment.java)
<img width="1436" alt="Screen Shot 2021-12-10 at 10 08 44 AM" src="https://user-images.githubusercontent.com/54903217/145621332-a0b505b0-ed87-436f-b1b8-7fa316b355f0.png">


Unit #2 FRQ deployed

- [ ] 1.0
- [x] .75
- [ ] .5
- [ ] 0
Justification:
- The storing of comments has an implantation of the FRQ. However, there is no JSON file and we need one to store the data. 
- [FRQ Implementation](https://github.com/ChristopherDuroiu/usb-c/blob/main/src/main/java/com/example/sping_portfolio/controllers/chris/UserComment.java)

**Comment by Navodit1603** [comment]
Team
README quality, release day policies, Scrum Board to week after break

- [x] 1.0
- [ ] .75
- [ ] .5
 - [ ] 0

Justification: [Readme](https://github.com/ChristopherDuroiu/usb-c)
- Readme has links and information about every group member
- It also has links to management plan, deployment plan and GitHub Plan


Team: Deployed Web Site

- [ ]  1.0
- [x] .75
- [ ] .5
- [ ] 0
Justification:
- Freenom site was not working and we ran into errors with jar files and maven packages.
