### ISSUE TITLE
Week 3 Review Ticket

### ISSUE THREAD

**Issue by calebkimsd** [ChristopherDuroiu/usb-c#22]
Navodit Maheshwari: 4.25/5 team, 2/2 <[frq2](http://dnstonks.cf/navodit/frq1) [frq3](http://dnstonks.cf/navodit/frq2)>: 6.25/7
Grace Le: 4.25/5 team, 1.5/2 <[FRQs](http://dnstonks.cf/grace)>: 5.75/7
Caleb Kim: 4.25/5 team, 2/2 <[FRQ2](http://dnstonks.cf/caleb3) [FRQ3](http://dnstonks.cf/caleb2)>: 8.25/7, + 2 extra credit <[LINK](https://docs.google.com/document/d/1Tm9nrMQ5W7ykt7gGdA_tNw4-gzuuj9Tad-J4yZfqMP0/edit)> Peer Graded: Arnav
Christopher Duroiu: 4.25/5 team, 1.5/2 <[FRQ2](https://github.com/ChristopherDuroiu/usb-c/blob/main/src/main/java/com/example/sping_portfolio/controllers/chris/UserComment.java) [FRQ3](https://github.com/ChristopherDuroiu/usb-c/blob/main/src/main/java/com/example/sping_portfolio/controllers/chris/Chrisfrq2.java)>: 5.75/7

**Comment by Navodit1603** [comment]
Individual Section.
FRQ 2 
[LightSequence Runtime](http://dnstonks.cf/navodit/frq1)
[LightSequence Class](https://github.com/ChristopherDuroiu/usb-c/blob/main/src/main/java/com/example/sping_portfolio/controllers/navodit/LightSequence.java)
[Light sequence Controller](https://github.com/ChristopherDuroiu/usb-c/blob/main/src/main/java/com/example/sping_portfolio/controllers/navodit/LightSequenceController.java)
[LightSequence Front](https://github.com/ChristopherDuroiu/usb-c/blob/main/src/main/resources/templates/navodit/frq1.html)

FRQ 3
[RSVP Runtime](http://dnstonks.cf/navodit/frq2)
[RSVP class](https://github.com/ChristopherDuroiu/usb-c/blob/main/src/main/java/com/example/sping_portfolio/controllers/navodit/Rsvp.java)
[RSVP Controller](https://github.com/ChristopherDuroiu/usb-c/blob/main/src/main/java/com/example/sping_portfolio/controllers/navodit/RsvpController.java)
[RSVP Frontend](https://github.com/ChristopherDuroiu/usb-c/blob/main/src/main/resources/templates/navodit/frq2.html)

Inputs are already inputted into the class since I could not figure out user inputs

**Comment by calebkimsd** [comment]
Individual Section.
FRQ 2: [Runtime](https://dnstonks.cf/caleb3) [Java](https://github.com/ChristopherDuroiu/usb-c/blob/main/src/main/java/com/example/sping_portfolio/controllers/caleb/Calebfrq2math.java) [Frontend](https://github.com/ChristopherDuroiu/usb-c/blob/main/src/main/resources/templates/caleb3.html)
FRQ 3 [Runtime](https://dnstonks.cf/caleb2) [Java](https://github.com/ChristopherDuroiu/usb-c/blob/main/src/main/java/com/example/sping_portfolio/controllers/caleb/calebfrq3rsvp.java) [Frontend](https://github.com/ChristopherDuroiu/usb-c/blob/main/src/main/resources/templates/caleb2.html)
[Extra credit](https://docs.google.com/document/d/1Tm9nrMQ5W7ykt7gGdA_tNw4-gzuuj9Tad-J4yZfqMP0/edit)
Accessed in About Page: 
![image](https://user-images.githubusercontent.com/89210382/146507343-36b8cc25-1098-42a2-9601-e5bcf9874d3c.png)

(If Runtime link takes too long to load, copy/paste link to browser; https://dnstonks.cf/caleb3    -    https://dnstonks.cf/caleb2)

**Comment by gracele246** [comment]
Grace Individual Section
FRQ 3 [Code](https://github.com/ChristopherDuroiu/usb-c/blob/main/src/main/resources/static/text/gracefrq/Grace3FRQ.txt) | [Runtime](http://dnstonks.cf/grace) | [Frontend](https://github.com/ChristopherDuroiu/usb-c/blob/c8ba9441f26b7cd16f4cdf628d6b654aeb2339f1/src/main/resources/templates/grace.html#L20-L25)
FRQ 2 [Code](https://github.com/ChristopherDuroiu/usb-c/blob/main/src/main/resources/static/text/gracefrq/Grace3FRQ.txt) | [Runtime](http://dnstonks.cf/grace) | [Frontend](https://github.com/ChristopherDuroiu/usb-c/blob/c8ba9441f26b7cd16f4cdf628d6b654aeb2339f1/src/main/resources/templates/grace.html#L26-L31)
[Extra Credit FRQ Exam](https://docs.google.com/document/d/1JLWFIXWiq6WLpqHH-unedwzbT-EiFDw_bFFt4lQ3d9A/edit?usp=sharing)

**Comment by ChristopherDuroiu** [comment]
Chris Individual Section
FRQ 3 [Code](https://github.com/ChristopherDuroiu/usb-c/blob/main/src/main/java/com/example/sping_portfolio/controllers/chris/Chrisfrq2.java) | [Runtime](http://dnstonks.cf/chris) | [Frontend](https://github.com/ChristopherDuroiu/usb-c/blob/main/src/main/resources/templates/chrisfrq2.html)
FRQ 2 [Code](https://github.com/ChristopherDuroiu/usb-c/blob/main/src/main/java/com/example/sping_portfolio/controllers/chris/UserComment.java) | [Runtime](http://dnstonks.cf/comment) | [Frontend](https://github.com/ChristopherDuroiu/usb-c/blob/main/src/main/resources/templates/comment.html) 
[Extra Credit FRQ Exam](https://docs.google.com/document/d/1cg4MkD59jjRz4nwdQI_08EwvJEccD0CMMcPaFDSIajM/edit?usp=sharing) peer graded by Raadwan

**Comment by Navodit1603** [comment]
# Team Section.
## Design Manager tangibles
- Layout. https://github.com/ChristopherDuroiu/usb-c/blob/main/src/main/resources/templates/layout.html
- Front End Feature Screens: 
http://dnstonks.cf/
http://dnstonks.cf/crypto
http://dnstonks.cf/comment
http://dnstonks.cf/draw
http://dnstonks.cf/navodit
http://dnstonks.cf/caleb
http://dnstonks.cf/grace
http://dnstonks.cf/chris
(If links do not work/take long to load, type it out in a seperate broswer)
## Scrum Master tangibles
- [GitHub README](https://github.com/ChristopherDuroiu/usb-c#readme)
- [GitHub Review](https://github.com/ChristopherDuroiu/usb-c/projects/1#column-16895367)
- [GitHub In Progress](https://github.com/ChristopherDuroiu/usb-c/projects/1#column-16895363)
- [GitHub Backlog for after tree](https://github.com/ChristopherDuroiu/usb-c/projects/1#column-16895360)
- [Scrum Board](https://github.com/ChristopherDuroiu/usb-c/projects/1)
## Technical officer tangibles
- Database with CRUD: [Backend](https://github.com/ChristopherDuroiu/usb-c/blob/main/src/main/java/com/example/sping_portfolio/controllers/chris/Comment.java)
- Runtime http://dnstonks.cf/comment
## Deployment manager tangibles
- [Update procedure](https://github.com/ChristopherDuroiu/usb-c/wiki/Deployment-Plan#deployment-update-procedure) <link to deployment guid that contains procedure for someone to make an update to deployment>
- [Nginx config](https://github.com/ChristopherDuroiu/usb-c/wiki/Deployment-Plan#nginx-config) <link to deployment guide containing paste of configuration file>
- [Service config](https://github.com/ChristopherDuroiu/usb-c/wiki/Deployment-Plan#service-config) <link to deployment guide containing paste of service file>
## GitHub admin tangibles
- [Deployment Plan](https://github.com/ChristopherDuroiu/usb-c/wiki/Deployment-Plan)
-  [Pull Request Plan](https://github.com/ChristopherDuroiu/usb-c/wiki/Github-Admins-Policy-Document)
